### ISSUE TITLE
Add hypothetical examples from HACSim paper

### ISSUE THREAD

**Issue by jphill01** [jphill01/HACSim-RShiny-App#14]
Right now, we have one hypothetical example that is preloaded (5 equally frequent haplotypes). It would be better to replace this with example (1) below and to add others as a dropdown menu if possible. 

(1) N = 100, Hstar = 10, probs = rep(1/Hstar, Hstar) # equally frequent haplotypes
(2) N = 100, Hstar = 10, probs = c(0.90, rep(0.10/9, 9)) # 1 dominant haplotypes
(3) N = 100, Hstar = 10, probs = c(rep(0.45, 2), rep(0.10/8, 8)) # 2 dominant haplotypes
(4) N = 100, Hstar = 10, probs = c(rep(0.30, 3), rep(0.10/7, 7)) # 3 dominant haplotypes

**Comment by nsingh34** [comment]
Added.
