### ISSUE TITLE
Fix some typos, etc. in Tutorial

### ISSUE THREAD

**Issue by jphill01** [jphill01/HACSim-RShiny-App#24]
- "Click on 'run simulation'..." should be "Click on 'RUN SIMULATION'..."
- "... proportion of haplotypes to recover, confidence level for calculations and plotting" should be "... proportion of haplotypes to recover, as well as confidence level for calculations and plotting"
- "To simulate real simulation" should be "To simulate real species, "
- "To simulate hypothetical simulation" should be "To simulate real species,"
- Mention hypothetical species before real species (just switch the order in which these are listed)
- "User has an option to input proportion of DNA sequences to subsample..." should be "Users have the option to input either the proportion of haplotype labels or DNA sequences to subsample, depending on whether hypothetical species or real species are being simulated. To do so, click the appropriate checkbox and enter the desired value in the input field."
- "Once all steps have been completed hit run." should be "Once all steps have been completed, click Run."

**Comment by nsingh34** [comment]
Resolved.
