### ISSUE TITLE
Correct grammar etc. in tutorial pictures

### ISSUE THREAD

**Issue by jphill01** [jphill01/HACSim-RShiny-App#25]
There are still several grammar errors needing correction in the tutorial pictures.

For instance,

When you list the constraints for each parameter such as "probs must have Hstar elements", please be consistent in whether or not you include punctuation at the end or not. For example, there should be a question mark after a question such as "Should a random subsample of haplotype labels or DNA sequences be taken?"

I also prefer the word "click/clicked" instead of "hit". The former sounds better.

**Comment by nsingh34** [comment]
Fixed.
