### ISSUE TITLE
Fix grammar issues

### ISSUE THREAD

**Issue by jphill01** [jphill01/HACSim-RShiny-App#30]
- First bullet in Tutorial should be "RUN SIMULATION" not "run simulation".
- In second bullet point, there is an extra comma between the words "recover" and "as". Remove one comma.
- "as well confidence level for calculations and plotting" should be "as well as the desired confidence level for calculations and plotting"
- In second image there is a typo. "select a simulation type:-". I think this should be "Select between simulating real or hypothetical species"
- In the third image, there are typos. "H*" should be "Hstar". There is also an unnecessary apostrophe "1'.". Please fix.
- In fourth image, "Once user hits run button a window will open" should be "When the Run button is clicked, a window will open."
- The logo in all pictures says "HACSIM" instead of "HACSim". Please fix.

**Comment by nsingh34** [comment]
Fixed.
