### ISSUE TITLE
Add required packages to app.R script

### ISSUE THREAD

**Issue by jphill01** [jphill01/HACSim-RShiny-App#9]
In the app.R script, there are a few packages that are required. However, not all of them are loaded unless a user has already installed the package.

For instance, the app requires the 'shinydashboardPlus' package. Thus, there should be a line indicating this.

For every package that is required, I suggest you do the following.

    # install.packages("shinydashboardPllus")
    library(shinydashboardPlus)

If you do this for every package that is needed to run the app successfully, a user (or me) looking at the code in the future will know precisely which packages are employed.

 Further, we want to enable users to run the app directly from the HACSim R package using a custom function called 'launchApp()'. This requires us to include relevant packages and functions in both the HACSim R package DESCRIPTION and NAMESPACE files.

**Comment by nsingh34** [comment]
All required libraries has been included into app.R. launchApp() will be written once app has reached its final version. Further relevant packages and functions in both the HACSim R package DESCRIPTION and NAMESPACE files will be added by the end of the semester.
